[[redirects]]
  from = "https://edu-nuakri.netlify.app/*"
  to = "https://edunaukri.in/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
